package main.java.bupt.wxy.bitmanipulation;

/**
 * Created by xiyuanbupt on 3/2/17.
 389. Find the Difference Add to List
 Description  Submission  Solutions
 Total Accepted: 55295
 Total Submissions: 108220
 Difficulty: Easy
 Contributors: Admin
 Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */
public class FindTheDifference {

    // 所有字母都出现了两遍, 之后后加的字母没有出现两遍
    public char findTheDifference(String s, String t) {
        int key=0;
        for(char c:s.toCharArray()){
            key^=(c-'a');
        }
        for(char c:t.toCharArray()){
            key^=(c-'a');
        }
        return (char)('a'+key);
    }
}
